client:
  server-port: 8080
  client-thresholds:
    timeout-in-seconds: 5
    initial-window-size: 1
    max-window-size: 20
    initial-sshthresh: 16
server:
  port: 8080
  congestion-thresholds:
    package-loss: 0.1
